name: i_torch
description: A simple Torch application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  torch_control: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  icons_launcher: ^1.1.9

flutter_icons:
  image_path: "assets/lg/ic_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/lg/ic_logo.png"
  ios: true
  android: true

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lg/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
